name = "trip-finance-workspace"
main = "src/worker.ts"
compatibility_date = "2026-10-09"

[[d1_databases]]
binding = "DB"
database_name = "trip-finance-workspace"
database_id = "421accfb-ae28-4f33-b7ef-4d25415a0d8c"
